<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>False</IsPackable>
    <Nullable>enable</Nullable>
    <RootNamespace>AvaloniaDemo</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Easily add pan and zoom functionality to your Avalonia apps using PanAndZoom control.</Description>
    <PackageTags>Pan;Zoom;Control;Xaml;Managed;C#</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <PublishTrimmed>False</PublishTrimmed>
    <PublishSingleFile>False</PublishSingleFile>
    <PublishReadyToRun>False</PublishReadyToRun>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <Import Project="..\..\build\Base.props" />
  <Import Project="..\..\build\ReferenceAssemblies.props" />
  <Import Project="..\..\build\Avalonia.props" />
  <Import Project="..\..\build\Avalonia.Diagnostics.props" />
  <Import Project="..\..\build\Avalonia.Themes.Fluent.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\PanAndZoom\PanAndZoom.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Avalonia" Version="12.1.1" />
    <PackageReference Update="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Update="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Update="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    <PackageReference Update="ProDiagnostics" Version="12.1.0.2" />
  </ItemGroup>

</Project>
