<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <Nullable>enable</Nullable>
    <RootNamespace>Avalonia.Controls.PanAndZoom</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>PanAndZoom</PackageId>
    <Description>Easily add pan and zoom functionality to your Avalonia apps using PanAndZoom control.</Description>
    <PackageTags>Avalonia;Pan;Zoom;Control;Xaml;Managed;C#"</PackageTags>
  </PropertyGroup>

  <Import Project="..\..\build\Base.props" />
  <Import Project="..\..\build\SignAssembly.props" />
  <Import Project="..\..\build\SourceLink.props" />
  <Import Project="..\..\build\ReferenceAssemblies.props" />
  <Import Project="..\..\build\Avalonia.props" />
  <ItemGroup>
    <PackageReference Update="Avalonia" Version="12.1.1" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>

</Project>
